import Foundation
import AppKit

/// Respects the markers apps put on the pasteboard to say "don't keep this".
///
/// Password managers flag their copies as concealed; some apps flag throwaway
/// copies as transient or auto-generated. Storing those in a searchable history
/// is exactly what a clipboard manager must not do, so Klippy skips them.
/// See http://nspasteboard.org for the convention.
enum ClipboardPrivacy {
    static let ignoreConcealedKey = "klippy.privacy.ignoreConcealed"

    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Apps that mark their copies inconsistently but should never be recorded.
    private static let alwaysSkipTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    static var ignoresConcealedContent: Bool {
        // Default on: a fresh install protects passwords before anyone opens settings.
        UserDefaults.standard.object(forKey: ignoreConcealedKey) as? Bool ?? true
    }

    /// True when the current pasteboard contents must not be stored.
    static func shouldSkip(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }

        for type in alwaysSkipTypes where types.contains(type) {
            return true
        }

        // Throwaway writes from automation tools (Alfred, Keyboard Maestro,
        // Raycast) are never something the user copied. They used to be gated
        // behind the password-manager toggle, so switching that off started
        // recording every scratch write those tools make.
        if types.contains(transient) || types.contains(autoGenerated) { return true }

        guard ignoresConcealedContent else { return false }
        return types.contains(concealed)
    }
}

/// Clips the user has marked as secret by hand.
///
/// The classifier only catches shapes it recognises (API keys, card numbers).
/// A loose password looks like ordinary text, so this lets one be hidden
/// explicitly rather than guessing with a heuristic that would mask real notes.
final class SecretStore: ObservableObject {
    static let shared = SecretStore()

    private static let key = "klippy.privacy.manualSecrets"
    private let defaults = UserDefaults.standard

    @Published private(set) var ids: Set<UUID> = []

    private init() {
        let stored = defaults.stringArray(forKey: Self.key) ?? []
        ids = Set(stored.compactMap(UUID.init(uuidString:)))
    }

    func contains(_ id: UUID) -> Bool { ids.contains(id) }

    /// Returns true when the clip is now marked secret.
    @discardableResult
    func toggle(_ id: UUID) -> Bool {
        if ids.contains(id) {
            ids.remove(id)
        } else {
            ids.insert(id)
        }
        persist()
        return ids.contains(id)
    }

    /// Deleting a clip used to leave its secret mark behind, so the stored set
    /// grew with ids of clips that no longer exist and never shrank.
    func forget(_ id: UUID) {
        guard ids.remove(id) != nil else { return }
        persist()
    }

    func forgetAll() {
        guard !ids.isEmpty else { return }
        ids.removeAll()
        persist()
    }

    private func persist() {
        defaults.set(ids.map(\.uuidString), forKey: Self.key)
    }
}
